# ***BenchMark***

In [1]:
from reporte_metricas import ReporteMetricas

report = ReporteMetricas()
df = report.load()

Loaded 8 report(s)

## ***Validation***

### ***macro avg***

In [2]:
dfval_macro = df.query("Type == 'val' and Class == 'macro avg'").drop(columns=['accuracy', 'log_loss', 'auc']).reset_index(drop=True)
dfval_macro.sort_values(by=['f1-score'], ascending=False, inplace=True)
dfval_macro

     Model Type      Class precision recall f1-score support
6  XGBOOST  val  macro avg      0.86  0.811    0.833  5085.0
2     LGBM  val  macro avg     0.849  0.803    0.824  5085.0
1      MLP  val  macro avg     0.807  0.769    0.786  5085.0
0       RF  val  macro avg     0.766  0.792    0.778  5085.0
5       RL  val  macro avg      0.72  0.771     0.74  5085.0
3      SVC  val  macro avg     0.736  0.639    0.673  5085.0
7      KNN  val  macro avg     0.736  0.639    0.673  5085.0
4     CART  val  macro avg     0.649  0.657    0.652  5085.0

### ***weighted avg***

In [3]:
dfval_weight = df.query("Type == 'val' and Class == 'weighted avg'").drop(columns=['accuracy', 'log_loss', 'auc']).reset_index(drop=True)
dfval_weight.sort_values(by=['f1-score'], ascending=False, inplace=True)
dfval_weight

     Model Type         Class precision recall f1-score support
6  XGBOOST  val  weighted avg     0.891  0.895    0.892  5085.0
2     LGBM  val  weighted avg     0.884  0.888    0.885  5085.0
1      MLP  val  weighted avg     0.859  0.864    0.861  5085.0
0       RF  val  weighted avg     0.857  0.849    0.852  5085.0
5       RL  val  weighted avg     0.833  0.815    0.822  5085.0
3      SVC  val  weighted avg     0.794  0.809    0.794  5085.0
7      KNN  val  weighted avg     0.794  0.809    0.794  5085.0
4     CART  val  weighted avg     0.761  0.754    0.757  5085.0

### ***Global***

In [4]:
df_val_global = df.query("Type == 'val' and Class == 'global'").drop(columns=['precision', 'recall', 'f1-score', 'support']).reset_index(drop=True)
df_val_global.sort_values(by=['auc'], ascending=False, inplace=True)
df_val_global

     Model Type   Class accuracy log_loss    auc
6  XGBOOST  val  global    0.895    0.294  0.967
2     LGBM  val  global    0.888    0.303  0.964
1      MLP  val  global    0.864    0.367   0.95
0       RF  val  global    0.849    0.463  0.949
5       RL  val  global    0.815    0.561  0.926
3      SVC  val  global    0.809    1.883    0.9
7      KNN  val  global    0.809    1.883    0.9
4     CART  val  global    0.754    0.752  0.843

## ***Test***

### ***macro avg***

In [5]:
dfval_macro = df.query("Type == 'test' and Class == 'macro avg'").drop(columns=['accuracy', 'log_loss', 'auc']).reset_index(drop=True)
dfval_macro.sort_values(by=['f1-score'], ascending=False, inplace=True)
dfval_macro

     Model  Type      Class precision recall f1-score support
6  XGBOOST  test  macro avg     0.844  0.808    0.825  6356.0
2     LGBM  test  macro avg     0.849  0.793    0.818  6355.0
1      MLP  test  macro avg     0.814  0.767    0.788  6355.0
0       RF  test  macro avg     0.771  0.789    0.779  6355.0
5       RL  test  macro avg     0.733  0.786    0.754  6356.0
3      SVC  test  macro avg     0.745  0.643    0.678  6356.0
7      KNN  test  macro avg     0.745  0.643    0.678  6356.0
4     CART  test  macro avg     0.649  0.657    0.653  6356.0

### ***weighted avg***

In [6]:
dfval_weight = df.query("Type == 'test' and Class == 'weighted avg'").drop(columns=['accuracy', 'log_loss', 'auc']).reset_index(drop=True)
dfval_weight.sort_values(by=['f1-score'], ascending=False, inplace=True)
dfval_weight

     Model  Type         Class precision recall f1-score support
6  XGBOOST  test  weighted avg     0.885  0.888    0.886  6356.0
2     LGBM  test  weighted avg     0.884  0.889    0.885  6355.0
1      MLP  test  weighted avg     0.861  0.866    0.862  6355.0
0       RF  test  weighted avg     0.856   0.85    0.852  6355.0
5       RL  test  weighted avg      0.84  0.823    0.829  6356.0
3      SVC  test  weighted avg     0.797  0.811    0.795  6356.0
7      KNN  test  weighted avg     0.797  0.811    0.795  6356.0
4     CART  test  weighted avg     0.762  0.757     0.76  6356.0

### ***Global***

In [7]:
df_val_global = df.query("Type == 'test' and Class == 'global'").drop(columns=['precision', 'recall', 'f1-score', 'support']).reset_index(drop=True)
df_val_global.sort_values(by=['auc'], ascending=False, inplace=True)
df_val_global

     Model  Type   Class accuracy log_loss    auc
2     LGBM  test  global    0.889    0.297  0.968
6  XGBOOST  test  global    0.888      0.3  0.966
0       RF  test  global     0.85    0.457  0.952
1      MLP  test  global    0.866    0.365  0.951
5       RL  test  global    0.823     0.55  0.926
3      SVC  test  global    0.811    1.926  0.894
7      KNN  test  global    0.811    1.926  0.894
4     CART  test  global    0.757    0.734  0.846